version: "3.9"
services:

  anigure:
    env_file:
      - .env
    image: rhinock/anigure:1.1
    container_name: anigure
    restart: on-failure
    ports:
      - "5050:5050"
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - sqlsystem:/var/opt/mssql/
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup

volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
