version: "3.9"
services:

  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  anigure:
    env_file:
      - .env
    build: .
    image: rhinock/anigure:2.6
    container_name: anigure
    restart: on-failure
    ports:
      - "44494:44494"
    depends_on:
      - postgres

volumes:
  db-data:
